/* eslint-disable @typescript-eslint/naming-convention */
// M歌单用
const REGION_COUNTRY_MAP = {
  400001: {
    COUNTRY_LIST: [
      'BM',
      'KY',
      'PM',
      'GL',
      'TT',
      'LC',
      'CA',
      'AG',
      'DM',
      'VI',
      'BL',
      'KN',
      'MS',
      'BZ',
      'US',
      'GP',
      'HT',
      'VC',
      'BQ',
      'BS',
      'AI',
      'JM',
      'MF',
      'AW',
      'SX',
      'TC',
      'GD',
      'BB',
      'MQ',
      'VG',
      'CW',
    ],
    DEFAULT_COUNTRY: 'US',
  },
  400011: {
    COUNTRY_LIST: ['CH', 'LU', 'LI', 'DE', 'AT'],
    DEFAULT_COUNTRY: 'DE',
  },
  400017: {
    COUNTRY_LIST: ['CZ', 'RO', 'SK', 'SI', 'HR', 'HU', 'BG'],
    DEFAULT_COUNTRY: 'CZ',
  },
  400007: {
    COUNTRY_LIST: [
      'EC',
      'CL',
      'VE',
      'PR',
      'GN',
      'HN',
      'GT',
      'BO',
      'NI',
      'SV',
      'CU',
      'CO',
      'AR',
      'PY',
      'PE',
      'CR',
      'DO',
      'PA',
      'UY',
    ],
    DEFAULT_COUNTRY: 'CO',
  },
  400019: {
    COUNTRY_LIST: ['ES'],
    DEFAULT_COUNTRY: 'ES',
  },
  400012: {
    COUNTRY_LIST: [
      'GE',
      'IL',
      'SM',
      'MK',
      'JE',
      'IM',
      'ME',
      'GG',
      'CD',
      'MT',
      'AL',
      'LV',
      'BA',
      'AD',
      'RS',
      'AZ',
      'FO',
      'GI',
      'EE',
      'LT',
      'SJ',
      'GR',
      'IE',
      'GB',
    ],
    DEFAULT_COUNTRY: 'GB',
  },
  400003: {
    COUNTRY_LIST: ['GW', 'MZ', 'GQ', 'AO', 'CV', 'PT', 'ST'],
    DEFAULT_COUNTRY: 'PT',
  },
  400014: {
    COUNTRY_LIST: ['IT'],
    DEFAULT_COUNTRY: 'IT',
  },
  400020: {
    COUNTRY_LIST: ['LK', 'PK', 'BD', 'IN'],
    DEFAULT_COUNTRY: 'IN',
  },
  400006: {
    COUNTRY_LIST: ['MX'],
    DEFAULT_COUNTRY: 'MX',
  },
  400015: {
    COUNTRY_LIST: ['NL', 'BE'],
    DEFAULT_COUNTRY: 'NL',
  },
  400016: {
    COUNTRY_LIST: ['NO', 'DK', 'SE', 'IS', 'FI'],
    DEFAULT_COUNTRY: 'SE',
  },
  400013: {
    COUNTRY_LIST: ['PF', 'FR', 'GF', 'MC', 'TF'],
    DEFAULT_COUNTRY: 'FR',
  },
  400018: {
    COUNTRY_LIST: ['PL'],
    DEFAULT_COUNTRY: 'PL',
  },
  400009: {
    COUNTRY_LIST: ['UZ', 'KZ', 'MD', 'BY', 'UA', 'RU'],
    DEFAULT_COUNTRY: 'RU',
  },
  400021: {
    COUNTRY_LIST: ['EN'],
    DEFAULT_COUNTRY: 'EN',
  },
  // 400027: {  // todo remove after 400062 work
  //     COUNTRY_LIST: ['DZ', 'SA', 'KW', 'TN', 'LB', 'DJ', 'OM', 'IQ', 'MR', 'LY', 'YE', 'QA', 'EG', 'KM', 'SY',
  //                    'JO', 'BH', 'SD', 'MA', 'SO', 'AE', 'PS'],
  //     DEFAULT_COUNTRY: 'SA'  // 搜索area_code时候的默认国家
  // },
  400045: {
    COUNTRY_LIST: ['ZA', 'NG', 'KE', 'ET', 'TZ', 'SD', 'UG', 'GH', 'SN'],
    DEFAULT_COUNTRY: 'ZA',
  },
  400048: {
    COUNTRY_LIST: ['BR'],
    DEFAULT_COUNTRY: 'BR',
  },
  400049: {
    COUNTRY_LIST: ['TR'],
    DEFAULT_COUNTRY: 'TR',
  },
  400061: {
    COUNTRY_LIST: ['AU', 'NZ'],
    DEFAULT_COUNTRY: 'AU',
  },
  400062: {
    COUNTRY_LIST: ['SA', 'AE', 'KW', 'BH', 'QA', 'OM'],
    DEFAULT_COUNTRY: 'SA',
  },
  400063: {
    COUNTRY_LIST: ['MA', 'DZ', 'TN', 'EG', 'LB', 'IQ', 'JO', 'SD', 'DJ', 'LY', 'PS', 'SY', 'YE', 'SO', 'MR', 'KM'],
    DEFAULT_COUNTRY: 'MA',
  },
  400050: {
    COUNTRY_LIST: ['JP'],
    DEFAULT_COUNTRY: 'JP',
  },
  400051: {
    COUNTRY_LIST: ['KR'],
    DEFAULT_COUNTRY: 'KR',
  },
  400052: {
    COUNTRY_LIST: ['MY'],
    DEFAULT_COUNTRY: 'MY',
  },
  400053: {
    COUNTRY_LIST: ['PH'],
    DEFAULT_COUNTRY: 'PH',
  },
  400054: {
    COUNTRY_LIST: ['TW'],
    DEFAULT_COUNTRY: 'TW',
  },
  400055: {
    COUNTRY_LIST: ['TH'],
    DEFAULT_COUNTRY: 'TH',
  },
  400056: {
    COUNTRY_LIST: ['ID'],
    DEFAULT_COUNTRY: 'ID',
  },
  400057: {
    COUNTRY_LIST: ['VN'],
    DEFAULT_COUNTRY: 'VN',
  },
  400059: {
    COUNTRY_LIST: ['SG'],
    DEFAULT_COUNTRY: 'SG',
  },
  400060: {
    COUNTRY_LIST: ['HK', 'MO'],
    DEFAULT_COUNTRY: 'HK',
  },
};

// legal文章跳转用
export const EEA_COUNTRY = [
  'AT',
  'BE',
  'BG',
  'HR',
  'CY',
  'CZ',
  'DE',
  'DK',
  'EE',
  'EL',
  'FI',
  'FR',
  'GB',
  'GR',
  'HU',
  'IE',
  'IT',
  'LV',
  'LT',
  'LU',
  'MT',
  'NL',
  'PL',
  'PT',
  'RO',
  'SK',
  'SI',
  'ES',
  'SE',
  'NO',
  'IS',
  'LI',
];

export const VA_REGION_COUNTRY = ['US', 'CA'];

export const PRIVACY_RTO_COUNTRY = [
  'AT',
  'BE',
  'BG',
  'HR',
  'CY',
  'CZ',
  'DE',
  'DK',
  'EE',
  'FI',
  'FR',
  'GB',
  'EL',
  'HU',
  'IE',
  'IT',
  'LV',
  'LT',
  'LU',
  'MT',
  'NL',
  'PL',
  'PT',
  'RO',
  'SK',
  'SI',
  'ES',
  'SE',
  'NO',
  'IS',
  'LI',
  'CH',
];

export default REGION_COUNTRY_MAP;
