export const LOCALES = [
  ['en'],
  ['ja', 'ja-jp', 'ja-jpan', 'ja-JP'],
  ['zh_Hant', 'zh_TW', 'zh-tw', 'zh-hk', 'zh-Hant', 'zh-Hant-TW'],
  ['id', 'id-id', 'in-id', 'in', 'id-ID'],
  ['ms', 'ms-bn', 'ms-my', 'ms-MY'],
  ['ceb', 'ceb-ph', 'ceb-PH'],
  ['cs', 'cs-cz', 'cs-CZ'],
  ['de', 'de-at', 'de-ch', 'de-de', 'de-li', 'de-lu', 'de-DE'],
  ['es', 'es-es', 'es-ES', 'es-xl'],
  ['fil', 'tl-ph', 'tl', 'fil-ph', 'fil-PH'],
  ['fr', 'fr-be', 'fr-ch', 'fr-fr', 'fr-lu', 'fr-mc'],
  ['fr_CA', 'fr-CA'],
  ['it', 'it-ch', 'it-it', 'it-IT'],
  ['hu', 'hu-hu', 'hu-HU'],
  ['nl', 'NL', 'nl-be', 'nl-nl', 'nl-NL'],
  ['pl', 'pl-pl', 'pl-PL'],
  ['pt_BR', 'pt-br', 'pt-BR', 'pu', 'pt', 'pt-pt'],
  ['ro', 'ro-ro', 'ro-RO'],
  ['jv', 'jv-jv', 'jv-ID'],
  ['vi', 'vi-vn', 'vi-VN'],
  ['tr', 'tr-tr', 'tr-TR'],
  ['el', 'el-gr', 'el-GR'],
  ['sv', 'sv-se', 'sv-SE'],
  ['ru', 'ru-ru', 'ru-RU', 'ru-kz', 'ru-KZ'],
  ['uk', 'uk-ua', 'uk-UA'],
  ['hi', 'hi-in', 'hi-IN'],
  ['bn', 'bn-in', 'bn-IN', 'bn-bd', 'bn-BD'],
  ['pa-IN', 'pa', 'pa-in', 'pa-IN'],
  ['gu', 'gu-in', 'gu-IN'],
  ['ml-IN', 'ml', 'ml_in', 'ml-in', 'ml-IN'],
  ['th', 'th-th', 'TH', 'th-TH'],
  ['my', 'my', 'my-mm', 'my-MM'],
  ['ko', 'ko-kr', 'ko-KR', 'ko-kore'],
  [
    'ar',
    'ar-ae',
    'ar-bh',
    'ar-dz',
    'ar-eg',
    'ar-iq',
    'ar-jo',
    'ar-kw',
    'ar-lb',
    'ar-ly',
    'ar-ma',
    'ar-mena',
    'ar-om',
    'ar-qa',
    'ar-sa',
    'ar-sy',
    'ar-tn',
    'ar-ye',
  ],
  ['ur', 'ur-pk', 'ur-PK'],
  ['km', 'km-KH'],
  ['he_IL', 'he-IL', 'he-il', 'he'],
  ['fi', 'fi-FI'],
  ['et', 'et-EE'],
  ['bg', 'bg-BG'],
  ['hr', 'hr-HR'],
  ['lv', 'lv-LV'],
  ['lo', 'lo-LA'],
  ['da', 'da-DK'],
  ['uz'],
  ['lt'],
  ['sk'],
  ['nb', 'nb-no', 'nb-NO'],
  ['mr'],
  ['zh_Hans', 'zh-Hans'],
  ['kk', 'kz', 'kk-kz'],
  ['az', 'az-AZ'],
  ['ga'],
  ['is'],
  ['sl'],
];

// Starling lang codes
const TIKTOK_WEB_NODE_LANGUAGE_LIST = [
  'en',
  'ar',
  'de-DE',
  'es',
  'fi-FI',
  'fr',
  'fr-CA',
  'id-ID',
  'ja-JP',
  'ko-KR',
  'ms-MY',
  'ru-RU',
  'th-TH',
  'tr-TR',
  'vi-VN',
  'zh-Hant-TW',
  'af-ZA',
  'he-IL',
  'jv-ID',
  'ceb-PH',
  'cs-CZ',
  'it-IT',
  'hu-HU',
  'nl-NL',
  'pl-PL',
  'pt-BR',
  'ro-RO',
  'sv-SE',
  'sw',
  'fil-PH',
  'el-GR',
  'zu-ZA',
  'uk-UA',
  'ur',
  'hi-IN',
  'bn-IN',
  'pa-IN',
  'gu',
  'ml-IN',
  'my-MM',
  'zh-Hans',
];

// This maps langs to the starling lang
export const ARTICLE_TO_NODE_LANG_MAP = TIKTOK_WEB_NODE_LANGUAGE_LIST.reduce((map, lang) => {
  const index = LOCALES.findIndex((langAliases) =>
    langAliases.find((alias) => alias.toLowerCase() === lang.toLowerCase()),
  );
  (LOCALES[index] || []).forEach((alias) => (map[alias] = lang));
  return map;
}, {} as { [key in string]: string });

// SUPPORT_LANGUAGE_LIST
export const SUPPORT_LANGUAGE_LIST = [
  { value: 'id', alias: 'id-ID', label: 'Bahasa Indonesia', children: [{ value: 'default', label: '' }] },
  { value: 'de', alias: 'de-DE', label: 'Deutsch', children: [{ value: 'default', label: '' }] },
  { value: 'en', alias: 'en', label: 'English', children: [{ value: 'default', label: '' }] },
  { value: 'es', alias: 'es', label: 'Español', children: [{ value: 'default', label: '' }] },
  { value: 'fr', alias: 'fr', label: 'Français', children: [{ value: 'default', label: '' }] },
  { value: 'it', alias: 'it-IT', label: 'Italiano', children: [{ value: 'default', label: '' }] },
  { value: 'pt_BR', alias: 'pt-BR', label: 'Português', children: [{ value: 'default', label: '' }] },
  { value: 'vi', alias: 'vi-VN', label: 'Tiếng Việt', children: [{ value: 'default', label: '' }] },
  { value: 'tr', alias: 'tr-TR', label: 'Türkçe', children: [{ value: 'default', label: '' }] },
  { value: 'ru', alias: 'ru-RU', label: 'Русский', children: [{ value: 'default', label: '' }] },
  { value: 'hi', alias: 'hi-IN', label: 'हिन्दी', children: [{ value: 'default', label: '' }] },
  { value: 'ko', alias: 'ko-KR', label: '한국어', children: [{ value: 'default', label: '' }] },
  { value: 'ja', alias: 'ja-JP', label: '日本語', children: [{ value: 'default', label: '' }] },
  { value: 'zh_Hant', alias: 'zh-Hant-TW', label: '繁體中文', children: [{ value: 'default', label: '' }] },
  { value: 'ar', alias: 'ar', label: 'العربية', children: [{ value: 'default', label: '' }] },
  { value: 'th', alias: 'TH', label: 'ภาษาไทย', children: [{ value: 'default', label: '' }] },
  { value: 'he_IL', alias: 'he-IL', label: 'עִבְרִית', children: [{ value: 'default', label: '' }] },
  { value: 'nl', alias: 'NL', label: 'Nederlands', children: [{ value: 'default', label: '' }] },
  // EEU - 5
  { value: 'cs', alias: 'cs-CZ', label: 'Čeština', children: [{ value: 'default', label: '' }] },
  { value: 'el', alias: 'el-GR', label: 'Ελληνικά', children: [{ value: 'default', label: '' }] },
  { value: 'pl', alias: 'pl-PL', label: 'Polski', children: [{ value: 'default', label: '' }] },
  { value: 'ro', alias: 'ro-RO', label: 'Română', children: [{ value: 'default', label: '' }] },
  { value: 'sv', alias: 'sv-SE', label: 'Svenska', children: [{ value: 'default', label: '' }] },
  // 03/15 new 2 languages
  { value: 'ga', alias: 'ga', label: 'Gaeilge', children: [{ value: 'default', label: '' }] },
  { value: 'is', alias: 'is', label: 'Íslenska', children: [{ value: 'default', label: '' }] },
  // 12/18 new 3 languages
  { value: 'hu', alias: 'hu-HU', label: 'Magyar', children: [{ value: 'default', label: '' }] },
  { value: 'kk', alias: 'kk', label: 'қазақ тілі', children: [{ value: 'default', label: '' }] },
  { value: 'uz', alias: 'uz', label: 'Uzbek', children: [{ value: 'default', label: '' }] },
  // 7/26 new 10 languages
  { value: 'bg', alias: 'bg', label: 'български език', children: [{ value: 'default', label: '' }] },
  { value: 'hr', alias: 'hr', label: 'Hrvatski jezik', children: [{ value: 'default', label: '' }] },
  { value: 'da', alias: 'da', label: 'Dansk', children: [{ value: 'default', label: '' }] },
  { value: 'et', alias: 'et', label: 'Eesti keel', children: [{ value: 'default', label: '' }] },
  { value: 'fi', alias: 'fi-FI', label: 'Suomi', children: [{ value: 'default', label: '' }] },
  { value: 'lv', alias: 'lv', label: 'Latviešu valoda', children: [{ value: 'default', label: '' }] },
  { value: 'lt', alias: 'lt', label: 'Lietuvių kalba', children: [{ value: 'default', label: '' }] },
  { value: 'nb', alias: 'nb', label: 'Norsk bokmål', children: [{ value: 'default', label: '' }] },
  { value: 'sk', alias: 'sk', label: 'Slovenčina', children: [{ value: 'default', label: '' }] },
  { value: 'sl', alias: 'sl', label: 'Slovenski jezik', children: [{ value: 'default', label: '' }] },
];

export const ROW_LANGS = [
  { lang: 'en', countryCode: '' },
  { lang: 'es', countryCode: 'MX' },
  { lang: 'ar', countryCode: 'SA' },
  { lang: 'pt-BR', countryCode: 'BR' },
  { lang: 'vi', countryCode: 'VN' },
  { lang: 'tr', countryCode: 'TR' },
  { lang: 'ja', countryCode: 'JP' },
  { lang: 'ko', countryCode: 'KR' },
  { lang: 'ru', countryCode: 'RU' },
  { lang: 'tr', countryCode: 'TR' },
  { lang: 'th', countryCode: 'TH' },
  { lang: 'id', countryCode: 'ID' },
  { lang: 'hi', countryCode: 'IN' },
  { lang: 'pt_BR', countryCode: 'BR' },
  { lang: 'zh_Hant', countryCode: 'TW' },
  { lang: 'bn', countryCode: '' },
  { lang: 'ms', countryCode: 'MY' },
];

export const EEA_LANGS = [
  { lang: 'de', countryCode: 'AT' },
  { lang: 'nl', countryCode: 'BE' },
  { lang: 'en', countryCode: 'BG' },
  { lang: 'de', countryCode: 'CH' },
  { lang: 'el', countryCode: 'CY' },
  { lang: 'cs', countryCode: 'CZ' },
  { lang: 'de', countryCode: 'DE' },
  { lang: 'en', countryCode: 'DK' },
  { lang: 'en', countryCode: 'EE' },
  { lang: 'es', countryCode: 'ES' },
  { lang: 'fi', countryCode: 'FI' },
  { lang: 'fr', countryCode: 'FR' },
  { lang: 'en', countryCode: 'GB' },
  { lang: 'el', countryCode: 'GR' },
  { lang: 'en', countryCode: 'HR' },
  { lang: 'hu', countryCode: 'HU' },
  { lang: 'en', countryCode: 'IE' },
  { lang: 'en', countryCode: 'IS' },
  { lang: 'it', countryCode: 'IT' },
  { lang: 'de', countryCode: 'LI' },
  { lang: 'en', countryCode: 'LT' },
  { lang: 'en', countryCode: 'LU' },
  { lang: 'en', countryCode: 'LV' },
  { lang: 'en', countryCode: 'MT' },
  { lang: 'nl', countryCode: 'NL' },
  { lang: 'en', countryCode: 'NO' },
  { lang: 'pl', countryCode: 'PL' },
  { lang: 'pt_BR', countryCode: 'PT' },
  { lang: 'ro', countryCode: 'RO' },
  { lang: 'sv', countryCode: 'SE' },
  { lang: 'en', countryCode: 'SI' },
  { lang: 'en', countryCode: 'SK' },
];
